import {
  FaFacebookF,
  FaTwitter,
  FaInstagram,
  FaLinkedinIn,
  FaGithub,
  FaYoutube,
  FaPinterest,
  FaWhatsapp,
  FaTelegramPlane,
  FaDiscord,
  FaDribbble,
  FaReddit,
  FaTwitch,
} from "react-icons/fa";

export const iconMap = {
  Facebook: FaFacebookF,
  Twitter: FaTwitter,
  Instagram: FaInstagram,
  LinkedIn: FaLinkedinIn,
  GitHub: FaGithub,
  YouTube: FaYoutube,
  Pinterest: FaPinterest,
  WhatsApp: FaWhatsapp,
  Telegram: FaTelegramPlane,
  Discord: FaDiscord,
  Dribbble: FaDribbble,
  Reddit: FaReddit,
  Twitch: FaTwitch,
};
